
#jwt:
#  security: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByYK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY


#Google authentication
# url format:- /oauth2/authorization/google
spring:
  application:
    name: USER-AUTH
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 300671420741-emb49ot8nhrrj8fcvrr114fvciprsop4.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
      instance:
        hostname: localhost


